<?php

namespace AppBundle\Repository;

/**
 * Message_sectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Message_sectionRepository extends \Doctrine\ORM\EntityRepository
{
}
